#------------ Project Information ------------
site_name: LABORATORIO - Comparar el tamaño de dos cadenas de texto (strings) 
site_url: 
site_author: Adriel E. González Martínez
site_description: >-
  Create a branded static site from a set of Markdown files to host the
  documentation of your Open Source or commercial project

### Copyright ### 
copyright: Copyright &copy; 2022 <a href="http://forwardlearning.com">Forward Learning</a>

### Version control & repository  ###
#repo_name: paloooo/IntroToProgrammingDocs
#repo_url: https://github.com/paloooo/IntroToProgramming

#------------ ends ------------  

#---------- Theme configuration ----------

theme:
  name: material
  custom_dir: material

 
### Static files ###
  static_templates:
    - 404.html

# Note:  Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: false

# Note: Default values, taken from mkdocs_theme.yml
  language: es #Site locale & language set to español
  

#----- Theme features -----
  features:

###  Site navigation features  ### 
    - navigation.search
    - navigation.indexes
  # - navigation.instant
    - navigation.tabs # Tabs menus under the header 
  # - navigation.tabs.sticky # Sticky tabs shows when scrolling - DISABLE
    - navigation.sections # Left sidebar menu 
  # - navigation.expand # Left sidebar menu expands by default - DISABLE
    - navigation.tracking
    - navigation.top # Back to top buttom 

### Site Search & index features ###     
    - search.highlight
    - search.share
    - search.suggest

### Table of contents (toc) features ### 
    - toc.follow
    # - toc.integrate - DISABLE

### Site header features ### 
  # - header.autohide # Autohide the header when scrolling - DISABLE

### Content display features ### 
    - content.code.annotate
  # - content.tabs.link - DISABLE
    - content.tooltips

#----- ends -----
   
palette:
  scheme: default
  primary: deep purple
  accent: deep purple
#--- Site fonts --- 
font:
  text: Roboto
  code: Roboto Mono

#--- HACK the theme!!! 
extra_css:
  - stylesheets/custom.css

#--- Theme Plugins ---
plugins:
  - search
  #- minify:
      #minify_html: true
      #minify_js: true
  - include-markdown
#----- Theme configuration ends -----

#---------- Markdown Extensions ----------
markdown_extensions:
  - md_in_html
  - meta
  - admonition
  - attr_list
  - def_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details

  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true

  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

#---------- ends ----------

#---------- Site Tree & Navigation  ----------
nav:
  - Inicio: index.md
  
  
#---------- ends ---------- 
